use_frameworks!

platform :ios, '8.0'

target 'GSHOpenSDK_Example' do
  pod 'GSHOpenSDK', :path => '../'

  target 'GSHOpenSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
