// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ProtocolNode;
@class ProtocolNodeAttribute;
@class ProtocolNodeMap;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProtocolRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProtocolRoot : GPBRootObject
@end

#pragma mark - ProtocolNodeAttribute

typedef GPB_ENUM(ProtocolNodeAttribute_FieldNumber) {
  ProtocolNodeAttribute_FieldNumber_Name = 1,
  ProtocolNodeAttribute_FieldNumber_Value = 2,
};

@interface ProtocolNodeAttribute : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - ProtocolNodeMap

typedef GPB_ENUM(ProtocolNodeMap_FieldNumber) {
  ProtocolNodeMap_FieldNumber_Name = 1,
  ProtocolNodeMap_FieldNumber_NodeArray = 2,
};

@interface ProtocolNodeMap : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProtocolNode*> *nodeArray;
/** The number of items in @c nodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nodeArray_Count;

@end

#pragma mark - ProtocolNode

typedef GPB_ENUM(ProtocolNode_FieldNumber) {
  ProtocolNode_FieldNumber_IsCdata = 1,
  ProtocolNode_FieldNumber_Name = 2,
  ProtocolNode_FieldNumber_Value = 3,
  ProtocolNode_FieldNumber_AttrArray = 4,
  ProtocolNode_FieldNumber_NodeArray = 5,
};

@interface ProtocolNode : GPBMessage

@property(nonatomic, readwrite) BOOL isCdata;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProtocolNodeAttribute*> *attrArray;
/** The number of items in @c attrArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attrArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProtocolNodeMap*> *nodeArray;
/** The number of items in @c nodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nodeArray_Count;

@end

#pragma mark - Protocol_Class

typedef GPB_ENUM(Protocol_Class_FieldNumber) {
  Protocol_Class_FieldNumber_Id_p = 1,
  Protocol_Class_FieldNumber_Sn = 2,
  Protocol_Class_FieldNumber_GwId = 3,
  Protocol_Class_FieldNumber_ErrCode = 4,
  Protocol_Class_FieldNumber_NodeArray = 5,
};

@interface Protocol_Class : GPBMessage

@property(nonatomic, readwrite) int32_t id_p;

@property(nonatomic, readwrite) int32_t sn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gwId;

@property(nonatomic, readwrite) int32_t errCode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProtocolNodeMap*> *nodeArray;
/** The number of items in @c nodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nodeArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
